// Kotlin bindings of clipsync-core, generated by UniFFI from the clipsync-ffi library (D2).

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.jvm)
}

val rustDir: File = rootDir.resolve("../linux").canonicalFile
val hostLibrary: File = rustDir.resolve("target/debug/libclipsync_ffi.so")

// Cargo decides what is up to date, so this always runs; it is a no-op when nothing changed.
val cargoBuildHost = tasks.register<Exec>("cargoBuildHost") {
    description = "Builds clipsync-ffi for this machine, for binding generation and the JVM tests."
    workingDir = rustDir
    commandLine("cargo", "build", "--locked", "-p", "clipsync-ffi")
}

val generateBindings = tasks.register<Exec>("generateBindings") {
    description = "Generates the Kotlin bindings from the clipsync-ffi library."
    dependsOn(cargoBuildHost)
    val outDir = layout.buildDirectory.dir("generated/uniffi")
    inputs.file(hostLibrary)
    inputs.file(rustDir.resolve("crates/clipsync-ffi/uniffi.toml"))
    outputs.dir(outDir)
    workingDir = rustDir
    commandLine(
        "cargo", "run", "--locked", "-q", "-p", "clipsync-ffi", "--bin", "uniffi-bindgen", "--",
        "generate", "--no-format", "--language", "kotlin",
        "--library", hostLibrary.path, "--out-dir", outDir.get().asFile.path,
    )
}

kotlin {
    sourceSets.main { kotlin.srcDir(generateBindings) }
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
        // Generated code: its warnings are not ours to fix.
        suppressWarnings.set(true)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    // Consumers pick the JNA artifact: the jar on the JVM, the AAR (with its native part) on Android.
    compileOnly(libs.jna)
}
